# Data Exploration 01

A consumer watchdog group wants to see if Netflix has more movies for adults or children.

Using a dataset containing metadata for all of the movies Netflix had available on their platform in 2019, we'll use the MPAA movie rating system to determine if they are correct.

## MPAA Movie Ratings:
* G: All ages admitted.
* PG: Some material may not be suitable for children.
* PG-13: Some material may be inappropriate for children under 13.
* R: Under 17 requires accompanying parent or adult guardian
* NC-17: No One 17 and Under Admitted

Most people would consider G and PG as ratings suitable for children. However, not everyone would agree that a PG-13 movie is necssarily a children's movie. It is up to you to decide how to handle this.

## Part 1: Import Polars

The `polars library` is a python library used for data analysis and manipulation. It will provide the core functionality for most of what you do in the data exploration and preprocessing stages of most machine learning projects.

Please see [this Getting Started Guide](https://docs.pola.rs/user-guide/getting-started/) for information on the conventional way to import Polars into your project, as well as other helpful tips for common Polars tasks.

In [4]:
# Part 1: Enter the code below to import Polars according to the
# conventional method.
import polars as pl

## Part 2: Load the data

The dataset for this exploration is stored at the following url:

[https://raw.githubusercontent.com/byui-cse/cse450-course/master/data/netflix_titles.csv](https://raw.githubusercontent.com/byui-cse/cse450-course/master/data/netflix_titles.csv)

There are lots of ways to load data into your workspace. The easiest way in this case is to [ask Polars to do it for you](https://docs.pola.rs/user-guide/getting-started/#reading-writing).

### Initial Data Analysis
Once you've loaded the data, it's a good idea to poke around a little bit to find out what you're dealing with.

Some questions you might ask include:

* What does the data look like?
* What kind of data is in each column?
* Do any of the columns have missing values?

In [ ]:
# Part 2: Load the dataset into a Polars dataframe.

url = "https://raw.githubusercontent.com/byui-cse/cse450-course/master/data/netflix_titles.csv"
df = pl.read_csv(url)

In [10]:
# Then, explore the data by seeing what the first few rows look like.
df

shape: (6_234, 12)
┌──────────┬─────────┬────────────┬────────────┬───┬──────────┬────────────┬───────────┬───────────┐
│ show_id  ┆ type    ┆ title      ┆ director   ┆ … ┆ rating   ┆ duration   ┆ listed_in ┆ descripti │
│ ---      ┆ ---     ┆ ---        ┆ ---        ┆   ┆ ---      ┆ ---        ┆ ---       ┆ on        │
│ i64      ┆ str     ┆ str        ┆ str        ┆   ┆ str      ┆ str        ┆ str       ┆ ---       │
│          ┆         ┆            ┆            ┆   ┆          ┆            ┆           ┆ str       │
╞══════════╪═════════╪════════════╪════════════╪═══╪══════════╪════════════╪═══════════╪═══════════╡
│ 81145628 ┆ Movie   ┆ Norm of    ┆ Richard    ┆ … ┆ TV-PG    ┆ 90 min     ┆ Children  ┆ Before    │
│          ┆         ┆ the North: ┆ Finn, Tim  ┆   ┆          ┆            ┆ & Family  ┆ planning  │
│          ┆         ┆ King Sized ┆ Maltby     ┆   ┆          ┆            ┆ Movies,   ┆ an        │
│          ┆         ┆ …          ┆            ┆   ┆          ┆            ┆ Come…     ┆ awesome   │
│          ┆         ┆            ┆            ┆   ┆          ┆            ┆           ┆ wed…      │
│ 80117401 ┆ Movie   ┆ Jandino:   ┆ null       ┆ … ┆ TV-MA    ┆ 94 min     ┆ Stand-Up  ┆ Jandino   │
│          ┆         ┆ Whatever   ┆            ┆   ┆          ┆            ┆ Comedy    ┆ Asporaat  │
│          ┆         ┆ it Takes   ┆            ┆   ┆          ┆            ┆           ┆ riffs on  │
│          ┆         ┆            ┆            ┆   ┆          ┆            ┆           ┆ the …     │
│ 70234439 ┆ TV Show ┆ Transforme ┆ null       ┆ … ┆ TV-Y7-FV ┆ 1 Season   ┆ Kids' TV  ┆ With the  │
│          ┆         ┆ rs Prime   ┆            ┆   ┆          ┆            ┆           ┆ help of   │
│          ┆         ┆            ┆            ┆   ┆          ┆            ┆           ┆ three     │
│          ┆         ┆            ┆            ┆   ┆          ┆            ┆           ┆ human a…  │
│ 80058654 ┆ TV Show ┆ Transforme ┆ null       ┆ … ┆ TV-Y7    ┆ 1 Season   ┆ Kids' TV  ┆ When a    │
│          ┆         ┆ rs: Robots ┆            ┆   ┆          ┆            ┆           ┆ prison    │
│          ┆         ┆ in Disgui… ┆            ┆   ┆          ┆            ┆           ┆ ship      │
│          ┆         ┆            ┆            ┆   ┆          ┆            ┆           ┆ crash     │
│          ┆         ┆            ┆            ┆   ┆          ┆            ┆           ┆ unlea…    │
│ 80125979 ┆ Movie   ┆ #realityhi ┆ Fernando   ┆ … ┆ TV-14    ┆ 99 min     ┆ Comedies  ┆ When      │
│          ┆         ┆ gh         ┆ Lebrija    ┆   ┆          ┆            ┆           ┆ nerdy     │
│          ┆         ┆            ┆            ┆   ┆          ┆            ┆           ┆ high      │
│          ┆         ┆            ┆            ┆   ┆          ┆            ┆           ┆ schooler  │
│          ┆         ┆            ┆            ┆   ┆          ┆            ┆           ┆ Dani …    │
│ …        ┆ …       ┆ …          ┆ …          ┆ … ┆ …        ┆ …          ┆ …         ┆ …         │
│ 80000063 ┆ TV Show ┆ Red vs.    ┆ null       ┆ … ┆ NR       ┆ 13 Seasons ┆ TV Action ┆ This      │
│          ┆         ┆ Blue       ┆            ┆   ┆          ┆            ┆ & Adventu ┆ parody of │
│          ┆         ┆            ┆            ┆   ┆          ┆            ┆ re, TV    ┆ first-per │
│          ┆         ┆            ┆            ┆   ┆          ┆            ┆ Come…     ┆ son sh…   │
│ 70286564 ┆ TV Show ┆ Maron      ┆ null       ┆ … ┆ TV-MA    ┆ 4 Seasons  ┆ TV        ┆ Marc      │
│          ┆         ┆            ┆            ┆   ┆          ┆            ┆ Comedies  ┆ Maron     │
│          ┆         ┆            ┆            ┆   ┆          ┆            ┆           ┆ stars as  │
│          ┆         ┆            ┆            ┆   ┆          ┆            ┆           ┆ Marc      │
│          ┆         ┆            ┆            ┆   ┆          ┆            ┆           ┆ Maron…    │
│ 80116008 ┆ Movie   ┆ Little     ┆ null       ┆ … ┆ null     ┆ 60 min     ┆ Movies    ┆ Nursery   │
│          ┆         ┆ Baby Bum:  ┆            ┆   ┆          ┆            ┆           ┆ rhymes    │
│          ┆         ┆ Nursery    ┆            ┆   ┆          ┆            ┆           ┆ and       │
│          ┆         ┆ Rhyme…     ┆            ┆   ┆          ┆            ┆           ┆ original  │
│          ┆         ┆            ┆            ┆   ┆          ┆            ┆           ┆ mu…       │
│ 70281022 ┆ TV Show ┆ A Young    ┆ null       ┆ … ┆ TV-MA    ┆ 2 Seasons  ┆ British   ┆ Set       │
│          ┆         ┆ Doctor's   ┆            ┆   ┆          ┆            ┆ TV Shows, ┆ during    │
│          ┆         ┆ Notebook   ┆            ┆   ┆          ┆            ┆ TV Comedi ┆ the       │
│          ┆         ┆ and …      ┆            ┆   ┆          ┆            ┆ es,…      ┆ Russian   │
│          ┆         ┆            ┆            ┆   ┆          ┆            ┆           ┆ Revolut…  │
│ 70153404 ┆ TV Show ┆ Friends    ┆ null       ┆ … ┆ TV-14    ┆ 10 Seasons ┆ Classic & ┆ This hit  │
│          ┆         ┆            ┆            ┆   ┆          ┆            ┆ Cult TV,  ┆ sitcom    │
│          ┆         ┆            ┆            ┆   ┆          ┆            ┆ TV        ┆ follows   │
│          ┆         ┆            ┆            ┆   ┆          ┆            ┆ Comedies  ┆ the me…   │
└──────────┴─────────┴────────────┴────────────┴───┴──────────┴────────────┴───────────┴───────────┘

In [15]:
# Next, display a technical summary of the data to determine the data types of each column, and which columns have missing data.
df.describe

<bound method DataFrame.describe of shape: (6_234, 12)
┌──────────┬─────────┬────────────┬────────────┬───┬──────────┬────────────┬───────────┬───────────┐
│ show_id  ┆ type    ┆ title      ┆ director   ┆ … ┆ rating   ┆ duration   ┆ listed_in ┆ descripti │
│ ---      ┆ ---     ┆ ---        ┆ ---        ┆   ┆ ---      ┆ ---        ┆ ---       ┆ on        │
│ i64      ┆ str     ┆ str        ┆ str        ┆   ┆ str      ┆ str        ┆ str       ┆ ---       │
│          ┆         ┆            ┆            ┆   ┆          ┆            ┆           ┆ str       │
╞══════════╪═════════╪════════════╪════════════╪═══╪══════════╪════════════╪═══════════╪═══════════╡
│ 81145628 ┆ Movie   ┆ Norm of    ┆ Richard    ┆ … ┆ TV-PG    ┆ 90 min     ┆ Children  ┆ Before    │
│          ┆         ┆ the North: ┆ Finn, Tim  ┆   ┆          ┆            ┆ & Family  ┆ planning  │
│          ┆         ┆ King Sized ┆ Maltby     ┆   ┆          ┆            ┆ Movies,   ┆ an        │
│          ┆         ┆ …          ┆            ┆   ┆          ┆            ┆ Come…     ┆ awesome   │
│          ┆         ┆            ┆            ┆   ┆          ┆            ┆           ┆ wed…      │
│ 80117401 ┆ Movie   ┆ Jandino:   ┆ null       ┆ … ┆ TV-MA    ┆ 94 min     ┆ Stand-Up  ┆ Jandino   │
│          ┆         ┆ Whatever   ┆            ┆   ┆          ┆            ┆ Comedy    ┆ Asporaat  │
│          ┆         ┆ it Takes   ┆            ┆   ┆          ┆            ┆           ┆ riffs on  │
│          ┆         ┆            ┆            ┆   ┆          ┆            ┆           ┆ the …     │
│ 70234439 ┆ TV Show ┆ Transforme ┆ null       ┆ … ┆ TV-Y7-FV ┆ 1 Season   ┆ Kids' TV  ┆ With the  │
│          ┆         ┆ rs Prime   ┆            ┆   ┆          ┆            ┆           ┆ help of   │
│          ┆         ┆            ┆            ┆   ┆          ┆            ┆           ┆ three     │
│          ┆         ┆            ┆            ┆   ┆          ┆            ┆           ┆ human a…  │
│ 80058654 ┆ TV Show ┆ Transforme ┆ null       ┆ … ┆ TV-Y7    ┆ 1 Season   ┆ Kids' TV  ┆ When a    │
│          ┆         ┆ rs: Robots ┆            ┆   ┆          ┆            ┆           ┆ prison    │
│          ┆         ┆ in Disgui… ┆            ┆   ┆          ┆            ┆           ┆ ship      │
│          ┆         ┆            ┆            ┆   ┆          ┆            ┆           ┆ crash     │
│          ┆         ┆            ┆            ┆   ┆          ┆            ┆           ┆ unlea…    │
│ 80125979 ┆ Movie   ┆ #realityhi ┆ Fernando   ┆ … ┆ TV-14    ┆ 99 min     ┆ Comedies  ┆ When      │
│          ┆         ┆ gh         ┆ Lebrija    ┆   ┆          ┆            ┆           ┆ nerdy     │
│          ┆         ┆            ┆            ┆   ┆          ┆            ┆           ┆ high      │
│          ┆         ┆            ┆            ┆   ┆          ┆            ┆           ┆ schooler  │
│          ┆         ┆            ┆            ┆   ┆          ┆            ┆           ┆ Dani …    │
│ …        ┆ …       ┆ …          ┆ …          ┆ … ┆ …        ┆ …          ┆ …         ┆ …         │
│ 80000063 ┆ TV Show ┆ Red vs.    ┆ null       ┆ … ┆ NR       ┆ 13 Seasons ┆ TV Action ┆ This      │
│          ┆         ┆ Blue       ┆            ┆   ┆          ┆            ┆ & Adventu ┆ parody of │
│          ┆         ┆            ┆            ┆   ┆          ┆            ┆ re, TV    ┆ first-per │
│          ┆         ┆            ┆            ┆   ┆          ┆            ┆ Come…     ┆ son sh…   │
│ 70286564 ┆ TV Show ┆ Maron      ┆ null       ┆ … ┆ TV-MA    ┆ 4 Seasons  ┆ TV        ┆ Marc      │
│          ┆         ┆            ┆            ┆   ┆          ┆            ┆ Comedies  ┆ Maron     │
│          ┆         ┆            ┆            ┆   ┆          ┆            ┆           ┆ stars as  │
│          ┆         ┆            ┆            ┆   ┆          ┆            ┆           ┆ Marc      │
│          ┆         ┆            ┆            ┆   ┆          ┆            ┆           ┆ Maron…    │
│ 80116008 ┆ Movie   ┆ Little     ┆ null       ┆ … ┆ null     ┆ 60 min     ┆ Movies    ┆ Nursery   │
│          ┆         ┆ Baby Bum:  ┆            ┆   ┆          ┆            ┆           ┆ rhymes    │
│          ┆         ┆ Nursery    ┆            ┆   ┆          ┆            ┆           ┆ and       │
│          ┆         ┆ Rhyme…     ┆            ┆   ┆          ┆            ┆           ┆ original  │
│          ┆         ┆            ┆            ┆   ┆          ┆            ┆           ┆ mu…       │
│ 70281022 ┆ TV Show ┆ A Young    ┆ null       ┆ … ┆ TV-MA    ┆ 2 Seasons  ┆ British   ┆ Set       │
│          ┆         ┆ Doctor's   ┆            ┆   ┆          ┆            ┆ TV Shows, ┆ during    │
│          ┆         ┆ Notebook   ┆            ┆   ┆          ┆            ┆ TV Comedi ┆ the       │
│          ┆         ┆ and …      ┆            ┆   ┆          ┆            ┆ es,…      ┆ Russian   │
│          ┆         ┆            ┆            ┆   ┆          ┆            ┆           ┆ Revolut…  │
│ 70153404 ┆ TV Show ┆ Friends    ┆ null       ┆ … ┆ TV-14    ┆ 10 Seasons ┆ Classic & ┆ This hit  │
│          ┆         ┆            ┆            ┆   ┆          ┆            ┆ Cult TV,  ┆ sitcom    │
│          ┆         ┆            ┆            ┆   ┆          ┆            ┆ TV        ┆ follows   │
│          ┆         ┆            ┆            ┆   ┆          ┆            ┆ Comedies  ┆ the me…   │
└──────────┴─────────┴────────────┴────────────┴───┴──────────┴────────────┴───────────┴───────────┘>

## Part 3: Filter the Data

Since we're just interested in movies, we'll need to [filter out anything](https://pandas.pydata.org/docs/getting_started/intro_tutorials/03_subset_data.html) that isn't a movie for our analysis. The `type` feature contains this information.

Once we have the subset, we should see how many rows it contains. There are a [variety of ways to get the length of a data frame](https://stackoverflow.com/a/38025280/28106).

In [48]:
from re import M
# Use polars's filtering abilitites to select the subset of data
# that represents movies, then calculate how many rows are in the filtered data.
movie = df.filter(pl.col('type') == 'Movie')
movie

shape: (4_265, 12)
┌──────────┬───────┬─────────────┬─────────────┬───┬────────┬──────────┬─────────────┬─────────────┐
│ show_id  ┆ type  ┆ title       ┆ director    ┆ … ┆ rating ┆ duration ┆ listed_in   ┆ description │
│ ---      ┆ ---   ┆ ---         ┆ ---         ┆   ┆ ---    ┆ ---      ┆ ---         ┆ ---         │
│ i64      ┆ str   ┆ str         ┆ str         ┆   ┆ str    ┆ str      ┆ str         ┆ str         │
╞══════════╪═══════╪═════════════╪═════════════╪═══╪════════╪══════════╪═════════════╪═════════════╡
│ 81145628 ┆ Movie ┆ Norm of the ┆ Richard     ┆ … ┆ TV-PG  ┆ 90 min   ┆ Children &  ┆ Before      │
│          ┆       ┆ North: King ┆ Finn, Tim   ┆   ┆        ┆          ┆ Family      ┆ planning an │
│          ┆       ┆ Sized …     ┆ Maltby      ┆   ┆        ┆          ┆ Movies,     ┆ awesome     │
│          ┆       ┆             ┆             ┆   ┆        ┆          ┆ Come…       ┆ wed…        │
│ 80117401 ┆ Movie ┆ Jandino:    ┆ null        ┆ … ┆ TV-MA  ┆ 94 min   ┆ Stand-Up    ┆ Jandino     │
│          ┆       ┆ Whatever it ┆             ┆   ┆        ┆          ┆ Comedy      ┆ Asporaat    │
│          ┆       ┆ Takes       ┆             ┆   ┆        ┆          ┆             ┆ riffs on    │
│          ┆       ┆             ┆             ┆   ┆        ┆          ┆             ┆ the …       │
│ 80125979 ┆ Movie ┆ #realityhig ┆ Fernando    ┆ … ┆ TV-14  ┆ 99 min   ┆ Comedies    ┆ When nerdy  │
│          ┆       ┆ h           ┆ Lebrija     ┆   ┆        ┆          ┆             ┆ high        │
│          ┆       ┆             ┆             ┆   ┆        ┆          ┆             ┆ schooler    │
│          ┆       ┆             ┆             ┆   ┆        ┆          ┆             ┆ Dani …      │
│ 70304989 ┆ Movie ┆ Automata    ┆ Gabe Ibáñez ┆ … ┆ R      ┆ 110 min  ┆ Internation ┆ In a        │
│          ┆       ┆             ┆             ┆   ┆        ┆          ┆ al Movies,  ┆ dystopian   │
│          ┆       ┆             ┆             ┆   ┆        ┆          ┆ Sci-Fi &…   ┆ future, an  │
│          ┆       ┆             ┆             ┆   ┆        ┆          ┆             ┆ insu…       │
│ 80164077 ┆ Movie ┆ Fabrizio    ┆ Rodrigo     ┆ … ┆ TV-MA  ┆ 60 min   ┆ Stand-Up    ┆ Fabrizio    │
│          ┆       ┆ Copano:     ┆ Toro,       ┆   ┆        ┆          ┆ Comedy      ┆ Copano      │
│          ┆       ┆ Solo pienso ┆ Francisco   ┆   ┆        ┆          ┆             ┆ takes       │
│          ┆       ┆ e…          ┆ Schult…     ┆   ┆        ┆          ┆             ┆ audience…   │
│ …        ┆ …     ┆ …           ┆ …           ┆ … ┆ …      ┆ …        ┆ …           ┆ …           │
│ 80085438 ┆ Movie ┆ Frank and   ┆ G.J.        ┆ … ┆ TV-MA  ┆ 70 min   ┆ Documentari ┆ Frank was a │
│          ┆       ┆ Cindy       ┆ Echternkamp ┆   ┆        ┆          ┆ es          ┆ rising pop  │
│          ┆       ┆             ┆             ┆   ┆        ┆          ┆             ┆ star wh…    │
│ 80085439 ┆ Movie ┆ Frank and   ┆ G.J.        ┆ … ┆ R      ┆ 102 min  ┆ Comedies,   ┆ A student   │
│          ┆       ┆ Cindy       ┆ Echternkamp ┆   ┆        ┆          ┆ Dramas,     ┆ filmmaker   │
│          ┆       ┆             ┆             ┆   ┆        ┆          ┆ Independent ┆ vengefully… │
│          ┆       ┆             ┆             ┆   ┆        ┆          ┆ …           ┆             │
│ 80011846 ┆ Movie ┆ Iverson     ┆ Zatella     ┆ … ┆ NR     ┆ 88 min   ┆ Documentari ┆ This        │
│          ┆       ┆             ┆ Beatty      ┆   ┆        ┆          ┆ es, Sports  ┆ unfiltered  │
│          ┆       ┆             ┆             ┆   ┆        ┆          ┆ Movies      ┆ documentary │
│          ┆       ┆             ┆             ┆   ┆        ┆          ┆             ┆ fo…         │
│ 80064521 ┆ Movie ┆ Jeremy      ┆ Vlad Yudin  ┆ … ┆ PG-13  ┆ 109 min  ┆ Documentari ┆ The journey │
│          ┆       ┆ Scott: The  ┆             ┆   ┆        ┆          ┆ es          ┆ of fashion  │
│          ┆       ┆ People's    ┆             ┆   ┆        ┆          ┆             ┆ designe…    │
│          ┆       ┆ Des…        ┆             ┆   ┆        ┆          ┆             ┆             │
│ 80116008 ┆ Movie ┆ Little Baby ┆ null        ┆ … ┆ null   ┆ 60 min   ┆ Movies      ┆ Nursery     │
│          ┆       ┆ Bum:        ┆             ┆   ┆        ┆          ┆             ┆ rhymes and  │
│          ┆       ┆ Nursery     ┆             ┆   ┆        ┆          ┆             ┆ original    │
│          ┆       ┆ Rhyme…      ┆             ┆   ┆        ┆          ┆             ┆ mu…         │
└──────────┴───────┴─────────────┴─────────────┴───┴────────┴──────────┴─────────────┴─────────────┘

### MPAA Ratings
Now that we have only movies, let's get a [quick count of the values being used](https://pandas.pydata.org/docs/getting_started/intro_tutorials/06_calculate_statistics.html)  in the `rating` feature.

In [44]:
# Determine the number of records for each value of the "rating" feature.
# Remember to count the values in your subset only, not in the original dataframe.
ratings = movie.select(pl.col('rating'))
ratings['rating'].value_counts()

shape: (15, 2)
┌──────────┬───────┐
│ rating   ┆ count │
│ ---      ┆ ---   │
│ str      ┆ u32   │
╞══════════╪═══════╡
│ TV-Y7    ┆ 69    │
│ G        ┆ 36    │
│ PG-13    ┆ 286   │
│ TV-Y7-FV ┆ 27    │
│ UR       ┆ 7     │
│ …        ┆ …     │
│ null     ┆ 8     │
│ NR       ┆ 202   │
│ TV-G     ┆ 80    │
│ TV-14    ┆ 1038  │
│ PG       ┆ 183   │
└──────────┴───────┘

### More Filtering

There are apparently some "made for TV" movies in the list that don't fit the
MPAA rating scheme.

Let's [filter some more](https://pandas.pydata.org/docs/getting_started/intro_tutorials/03_subset_data.html) to just see movies rated with the standard MPAA ratings of G, PG, PG-13, R, and NC-17.

In [50]:
# Filter the list of movies to select a new subset containing only movies with
# a standard MPAA rating. Calculate how many rows are in this new set, and
# then see which ratings appear most often.
mpaa = ['G', 'PG', 'PG-13', 'R', 'NC-17']
movie.filter(pl.col('rating').is_in(mpaa))

shape: (1_013, 12)
┌──────────┬───────┬─────────────┬─────────────┬───┬────────┬──────────┬─────────────┬─────────────┐
│ show_id  ┆ type  ┆ title       ┆ director    ┆ … ┆ rating ┆ duration ┆ listed_in   ┆ description │
│ ---      ┆ ---   ┆ ---         ┆ ---         ┆   ┆ ---    ┆ ---      ┆ ---         ┆ ---         │
│ i64      ┆ str   ┆ str         ┆ str         ┆   ┆ str    ┆ str      ┆ str         ┆ str         │
╞══════════╪═══════╪═════════════╪═════════════╪═══╪════════╪══════════╪═════════════╪═════════════╡
│ 70304989 ┆ Movie ┆ Automata    ┆ Gabe Ibáñez ┆ … ┆ R      ┆ 110 min  ┆ Internation ┆ In a        │
│          ┆       ┆             ┆             ┆   ┆        ┆          ┆ al Movies,  ┆ dystopian   │
│          ┆       ┆             ┆             ┆   ┆        ┆          ┆ Sci-Fi &…   ┆ future, an  │
│          ┆       ┆             ┆             ┆   ┆        ┆          ┆             ┆ insu…       │
│ 70304990 ┆ Movie ┆ Good People ┆ Henrik      ┆ … ┆ R      ┆ 90 min   ┆ Action &    ┆ A           │
│          ┆       ┆             ┆ Ruben Genz  ┆   ┆        ┆          ┆ Adventure,  ┆ struggling  │
│          ┆       ┆             ┆             ┆   ┆        ┆          ┆ Thrillers   ┆ couple      │
│          ┆       ┆             ┆             ┆   ┆        ┆          ┆             ┆ can't beli… │
│ 70299204 ┆ Movie ┆ Kidnapping  ┆ Daniel      ┆ … ┆ R      ┆ 95 min   ┆ Action &    ┆ When beer   │
│          ┆       ┆ Mr.         ┆ Alfredson   ┆   ┆        ┆          ┆ Adventure,  ┆ magnate     │
│          ┆       ┆ Heineken    ┆             ┆   ┆        ┆          ┆ Dramas, In… ┆ Alfred      │
│          ┆       ┆             ┆             ┆   ┆        ┆          ┆             ┆ "Fred…      │
│ 80046728 ┆ Movie ┆ Moonwalkers ┆ Antoine Bar ┆ … ┆ R      ┆ 96 min   ┆ Action &    ┆ A brain-add │
│          ┆       ┆             ┆ dou-Jacquet ┆   ┆        ┆          ┆ Adventure,  ┆ led war     │
│          ┆       ┆             ┆             ┆   ┆        ┆          ┆ Comedies, … ┆ vet, a      │
│          ┆       ┆             ┆             ┆   ┆        ┆          ┆             ┆ fail…       │
│ 70304988 ┆ Movie ┆ Stonehearst ┆ Brad        ┆ … ┆ PG-13  ┆ 113 min  ┆ Horror      ┆ In 1899, a  │
│          ┆       ┆ Asylum      ┆ Anderson    ┆   ┆        ┆          ┆ Movies,     ┆ young       │
│          ┆       ┆             ┆             ┆   ┆        ┆          ┆ Thrillers   ┆ doctor      │
│          ┆       ┆             ┆             ┆   ┆        ┆          ┆             ┆ arrive…     │
│ …        ┆ …     ┆ …           ┆ …           ┆ … ┆ …      ┆ …        ┆ …           ┆ …           │
│ 80049281 ┆ Movie ┆ Secret in   ┆ Billy Ray   ┆ … ┆ PG-13  ┆ 111 min  ┆ Dramas,     ┆ A former    │
│          ┆       ┆ Their Eyes  ┆             ┆   ┆        ┆          ┆ Thrillers   ┆ FBI investi │
│          ┆       ┆             ┆             ┆   ┆        ┆          ┆             ┆ gator reop… │
│ 70099610 ┆ Movie ┆ The Duchess ┆ Saul Dibb   ┆ … ┆ PG-13  ┆ 110 min  ┆ Dramas, Int ┆ To          │
│          ┆       ┆             ┆             ┆   ┆        ┆          ┆ ernational  ┆ compensate  │
│          ┆       ┆             ┆             ┆   ┆        ┆          ┆ Movies, …   ┆ for her     │
│          ┆       ┆             ┆             ┆   ┆        ┆          ┆             ┆ unhappy …   │
│ 80156408 ┆ Movie ┆ Una         ┆ Benedict    ┆ … ┆ R      ┆ 94 min   ┆ Dramas, Int ┆ A young     │
│          ┆       ┆             ┆ Andrews     ┆   ┆        ┆          ┆ ernational  ┆ woman       │
│          ┆       ┆             ┆             ┆   ┆        ┆          ┆ Movies      ┆ tracks down │
│          ┆       ┆             ┆             ┆   ┆        ┆          ┆             ┆ the …       │
│ 80085439 ┆ Movie ┆ Frank and   ┆ G.J.        ┆ … ┆ R      ┆ 102 min  ┆ Comedies,   ┆ A student   │
│          ┆       ┆ Cindy       ┆ Echternkamp ┆   ┆        ┆          ┆ Dramas,     ┆ filmmaker   │
│          ┆       ┆             ┆             ┆   ┆        ┆          ┆ Independent ┆ vengefully… │
│          ┆       ┆             ┆             ┆   ┆        ┆          ┆ …           ┆             │
│ 80064521 ┆ Movie ┆ Jeremy      ┆ Vlad Yudin  ┆ … ┆ PG-13  ┆ 109 min  ┆ Documentari ┆ The journey │
│          ┆       ┆ Scott: The  ┆             ┆   ┆        ┆          ┆ es          ┆ of fashion  │
│          ┆       ┆ People's    ┆             ┆   ┆        ┆          ┆             ┆ designe…    │
│          ┆       ┆ Des…        ┆             ┆   ┆        ┆          ┆             ┆             │
└──────────┴───────┴─────────────┴─────────────┴───┴────────┴──────────┴─────────────┴─────────────┘

## Part 4: Visualization
Now that we have explored and preprocessed our data, let's create a visualization to summarize our findings.

### Exploration vs Presentation
Broadly speaking, there are two types of visualizations:
* Barebones visualizations you might use to get a quick, visual understanding of the data while you're trying to decide how it all fits together.
* Presentation-quality visualizations that you would include in a report or presentation for management or other stakeholders.

### Visualization Tools
There are many different visualization tools availble. In the sections below,
we'll explore the three most common. Each of these libraries has strengths and weaknesses.

It is probably a good idea for you to become familiar with each one, and then become proficient at whichever one you like the best.

### Let's Plot
The Let's Plot visualization library uses a grammer of graphics to build up a chart piece by piece.


Assume we have a polars dataframe called `employees`, with three columns: `name`, `job`, `salary`.

    # Make a box plot style categorical plot showing the distribution of salaries for each job:
    ggplot(data=employees, aes(x='job', y='salary')) + geom_box()

    # Make a box plot style categorical plot, and customize the results
    (
        ggplot(data=employees, aes(x='job', y='salary'))
        + geom_boxplot()
        + labs(
            title='Salaries by Job Title'
        )
    )

Dependencies need to be installed in colab to use Let's Plot. Use `%pip` to install it. `%pip install lets-plot` will install the library, and skip it if it's already installed.

In [ ]:
# Install the lets-plot module into this server
%pip install lets-plot

*Like* with Polars, there is a [conventional way to import Let's Plot](https://lets-plot.org/python/index.html#python-index-user-guide) into your projects.

In [ ]:
# Import the Let's Plot library the conventional way.

Let's create a barchart showing the count of each movie rating by using Let's Plot's capabilities.

In [this example](https://aeturrell.github.io/python4DS/data-visualise.html#a-categorical-variable), we see the x axis being set to a feature called `species`, and the y axis is a count of the number of rows for that `species`.

In our case, we want the x-axis to be set to `rating`.

### Altair
The Altair visualization library provides a large variety of very easy to use statistical charting tools.

Altair uses a declarative language to build up charts piece by piece.

Assume we have a pandas dataframe called `employees`, with three columns: `name`, `job`, `salary`.

    # Make a box plot style categorical plot showing the distribution of salaries for each job:
    alt.Chart(employees).mark_boxplot().encode(
        x='job',
        y='salary'
    )

    # Make a box plot style categorical plot, and customize the results
    alt.Chart(employees).mark_boxplot().encode(
        alt.X('job', title='Job title'),
        alt.Y('salary', title='Annual salary in thousands of $USD')
    ).properties(
      title='Salaries by Job Title'
    )

*Like* with Polars, there is a [conventional way to import Altair](https://altair-viz.github.io/getting_started/starting.html#the-chart-object) into your projects.

In [ ]:
# Import the Altair library the conventional way.

Let's create a barchart showing the count of each movie rating by using Altair's aggregation capabilities.

In [this example](https://altair-viz.github.io/getting_started/starting.html#data-transformation-aggregation), we see the x axis being set to a feature called `a`, and the y axis set to the `average()` of a feature called `b`.

In our case, we want the x axis to be set to `rating` and the y axis to be the `count()` of `rating`.

In [ ]:
# Use Altair to create a bar chart comparing the count of each movie rating


### Seaborn
While Altair uses a "declarative" syntax for building charts piece by piece, the Seaborn library provides a large variety of pre-made charts for common statistical needs.

These charts are divided into different categories. Each category has a high-level interface you can use for simplicity, and then a specific function for each chart that you can use if you need more control over how the chart looks.

Seaborn uses matplotlib for its drawing, and the chart-specific functions each return a matplitlib axes object if you need additional customization.

For example, there are several different types of categorical plots in seaborn: bar plots, box plots, point plots, count plots, swarm plots, etc...

Each of these plots can be accessed using the `catplot` function.

Assume we have a pandas dataframe called `employees`, with three columns: `name`, `job`, `salary`.

    # Make a box plot style categorical plot showing the distribution of salaries for each job:
    sns.catplot(data=employees, x='job', y='salary', kind='box')

    # Make a swarm plot style categorical plot
    sns.catplot(data=employees, x='job', y='salary', kind='swarm')

Alternatively, you can use the plot specific functions to give yourself more control over the output by using matplotlib functions:

    # Make a box plot style categorical plot, and customize the results
    import matplotlib.pyplot as plt

    plt.figure(figsize=(12, 9))
    ax = sns.boxplot(data=employees, x='job', y='salary')
    ax.set_title("Salaries by Job Title")
    ax.set_ylabel("Annual salary in thousands of $USD")
    ax.set_xlabel("Job title")

Like with Polars, there is a [conventional way to import Seaborn](https://seaborn.pydata.org/tutorial/relational.html) into your projects.

Optionally, you may wish to set some default chart aesthetics by [setting the chart style](https://seaborn.pydata.org/tutorial/aesthetics.html).

In [ ]:
# Import the seaborn library the conventional way. Then optionally configure
# the default chart style.

Since the `rating` column uses categorical data, we need to use Seaborn's [categorical visualizations](https://seaborn.pydata.org/tutorial/categorical.html).

In particular, we want a "count plot" that will display a count of movie ratings.

In [ ]:
# Use seaborn to create a count plot comparing the count of each movie rating

# Part 5: Interpretation and Conclusions

Now that you've seen the data, what is your conclusion? Is the watchdog group
correct that Netflix has more movies for adults than for children? Are there any
caveats you'd include in your analysis?

Write your summary here:

## 🌟 Above and Beyond 🌟

After reviewing your findings, the watchdog group would like some additional questions answered:

1. How are things affected if you include the "made for TV movies" that have been assigned [TV ratings](https://en.wikipedia.org/wiki/Television_content_rating_system#United_States) in your analysis, but still exclude unrated movies?

2. They would also like to see a separate report that includes only TV shows.

3. For an upcoming community meeting, the group would like to present a simple
chart showing "For Kids" and "For Adults" categories. The easiest way to accomplish this would be to [create a new column in your data frame that maps](https://pandas.pydata.org/docs/getting_started/intro_tutorials/10_text_data.html) each rating to the appropriate "For Kids" or "For Adults" label, then create a new visualization based on that column.